[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[env]
  [env.production]
    NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
